### ISSUE TITLE
Better Inventory Generation

### ISSUE THREAD

**Issue by ghost** [KalmeMarq/Minecraft-JS#1]
`class PlayerInventory {
  constructor() {
    this.self = [
      { Slot: 0, Item: '', Count: 0 }, { Slot: 1, Item: '', Count: 0 }, { Slot: 2, Item: '', Count: 0 },
      { Slot: 3, Item: '', Count: 0 }, { Slot: 4, Item: '', Count: 0 }, { Slot: 5, Item: '', Count: 0 },
      { Slot: 6, Item: '', Count: 0 }, { Slot: 7, Item: '', Count: 0 }, { Slot: 8, Item: '', Count: 0 },
      { Slot: 9, Item: '', Count: 0 }, { Slot: 10, Item: '', Count: 0 }, { Slot: 11, Item: '', Count: 0 },
      { Slot: 12, Item: '', Count: 0 }, { Slot: 13, Item: '', Count: 0 }, { Slot: 14, Item: '', Count: 0 },
      { Slot: 15, Item: '', Count: 0 }, { Slot: 16, Item: '', Count: 0 }, { Slot: 17, Item: '', Count: 0 },
      { Slot: 18, Item: '', Count: 0 }, { Slot: 19, Item: '', Count: 0 }, { Slot: 20, Item: '', Count: 0 },
      { Slot: 21, Item: '', Count: 0 }, { Slot: 22, Item: '', Count: 0 }, { Slot: 23, Item: '', Count: 0 },
      { Slot: 24, Item: '', Count: 0 }, { Slot: 25, Item: '', Count: 0 }, { Slot: 26, Item: '', Count: 0 },
      { Slot: 18, Item: '', Count: 0 }, { Slot: 19, Item: '', Count: 0 }, { Slot: 20, Item: '', Count: 0 },
      { Slot: 21, Item: '', Count: 0 }, { Slot: 22, Item: '', Count: 0 }, { Slot: 23, Item: '', Count: 0 },
      { Slot: 24, Item: '', Count: 0 }, { Slot: 25, Item: '', Count: 0 }, { Slot: 26, Item: '', Count: 0 },
      { Slot: 27, Item: '', Count: 0 }, { Slot: 28, Item: '', Count: 0 }, { Slot: 29, Item: '', Count: 0 },
      { Slot: 30, Item: '', Count: 0 }
    ]
  }`
  
  Here you don't gotta specify every slot, instead you could generate it.
`
for (var i = 0; i < 30; ++i)
    this.self.push({ Slot: i, Item: "", Count: 0 });
`

**Comment by ghost** [comment]
I can't seem to figure out Github Markdown xD

**Comment by KalmeMarq** [comment]
I changed to this and I admit it's way better.

class Inventory {
  static playerHotbar() {
    let grid = [];
    for(let i = 0; i < 9; i++) {
      grid.push({ Slot: i, Item: '', Count: 0 })
    }
    return grid;
  }

  static playerInv() {
    let grid = [];
    for(let i = 9; i < 36; i++) {
      grid.push({ Slot: i, Item: '', Count: 0 })
    }
    return grid;
  }

  static playerArmor() {
    let grid = [];
    for(let i = 36; i < 40; i++) {
      grid.push({ Slot: i, Item: '', Count: 0 })
    }
    return grid;
  }

  static playerOffHand() {
    let grid = [];
    for(let i = 40; i < 41; i++) {
      grid.push({ Slot: i, Item: '', Count: 0 })
    }
    return grid;
  }

  static craftingSlots() {
    let grid = [];
    for(let i = 0; i < 9; i++) {
      grid.push({ Slot: i, Item: '', Count: 0 })
    }
    return grid;
  }

  static craftingOutput() {
    let grid = [];
    for(let i = 0; i < 1; i++) {
      grid.push({ Slot: i, Item: '', Count: 0 })
    }
    return grid;
  }

  static furnaceGrid() {
    let grid = [];
    for(let i = 0; i < 3; i++) {
      grid.push({ Slot: i, Item: '', Count: 0 })
    }
    return grid;
  }
}

**Comment by ghost** [comment]
👍
